{{ $bitnami := .Values.bitnami }}
{{- range $chart := $bitnami.charts }}
{{- $ns := (lookup "v1" "Namespace" "" $chart.name) -}}
{{- $managedByHelm := false }}
{{- if $ns }}
  {{- $managedByHelm = (get $ns.metadata.labels "app.kubernetes.io/managed-by" | eq "Helm") }}
{{- end }}

{{- if (or (not $ns) ($managedByHelm)) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $chart.name }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: {{ $chart.name }}
  namespace: helm-system
spec:
  targetNamespace: {{ $chart.name }}
  repo: https://charts.bitnami.com/bitnami
  chart: {{ $chart.name }}
  set: 
{{- if $chart.set }}
{{ $chart.set | toYaml | indent 4 }}
{{- end }}
{{- if $bitnami.set }}
{{ $bitnami.set | toYaml | indent 4 }}
{{- end }}
{{- end }}
---
{{- end }}