{{- range $tmpl := .Values.bitnamiTemplates -}}
{{- $ns := lookup "v1" "Namespace" "" $tmpl.name -}}
{{- if not $ns -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $tmpl.name }}
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: {{ $tmpl.name }}
  namespace: helm-system
spec:
  targetNamespace: {{ $tmpl.name }}
  repo: https://charts.bitnami.com/bitnami
  chart: {{ $tmpl.name }}
{{- if $tmpl.set -}}
  set: 
{{ $tmpl.set | toYaml | indent 4 }}
{{- end -}}
{{- end -}}
{{- end -}}